---
title: "R Notebook"
output: html_notebook
---

## Extinction function for foodweb



### P(extinction) increases assymptotically with the number of predators

```{r}
curve(pars$u_0 + pars$u_1 * exp(-pars$a_u * x), 
      xlab = "n predators",
      ylab = "p(extinction)")


curve(1 + -1 * exp(-0.45 * x), 
      xlab = "n predators",
      ylab = "p(extinction)")
```




### P(extinction) decreases assymptotically with the number of shared predators

```{r}


curve(0.075 + 5.19 * exp(-10 * x), 
      xlab = "In I",
      ylab = "p(extinction)")


curve(0.075 + 5.19 * exp(-10 * x), 
      xlab = "In I",
      ylab = "p(extinction)")


curve(0.1 * (1 - exp(-5*x)), 
      xlab = "Out I",
      ylab = "p(extinction)")
```


## Calculate  number of shared predators


```{r}
matrix <- round(matrix(runif(10,0,1), nrow=5, ncol=5), digits = 0)
mat
```



```{r}



pred_diet <- c()

shared_pred <- numeric(length(ncol(matrix)))

for (i in 1:ncol(matrix)) {
  
  for(j in 1:nrow(matrix)){
    
    if(matrix[j,i] == 1){
      
      pred_diet[j] <- sum(matrix[j,])
      
    }
    
    
  }
  
  
  shared_pred[i] <- sum(pred_diet)/length(pred_diet)
  
  
}

#sum(mat[which(mat[,2] == 1),])


```




```{r}

compute_shared_predators <- function(mat) {
  

pred_diet <- c()

shared_pred <- numeric(length(ncol(mat)))
  
  
for (i in 1:ncol(mat)) {
  
  for(j in 1:nrow(mat)){
    
    if(mat[j,i] == 1){
      
      pred_diet[j] <- sum(mat[j,])
      
    }
    
    
  }
  
  
  shared_pred[i] <- sum(pred_diet)/length(pred_diet)
  
  
}
  
  
  return(shared_pred)
  
}

matrix <- round(matrix(runif(10,0,1), nrow=5, ncol=5), digits = 0)


compute_shared_predators(mat = matrix)
```




```{r}

par(mfrow = c(1,3))

curve(0.1 + 1 * exp(-6 * x),
      cex = 5,
      xlab = "Species richness",
      ylab = "Trait directionality",
      col = "darkgoldenrod4",
      lwd = 3)

curve(0.1 + 1 * exp(3 * x),
      cex = 5,
      xlab = "Species richness",
      ylab = "Trait matching fluctuation",
      col = "darkgoldenrod4",
      lwd = 3)

curve(0.1 + 1 * exp(-6 * x),
      cex = 5,
      xlab = "Species richness",
      ylab = "Evolutionary rate",
      col = "darkgoldenrod4",
      lwd = 3)


```






















