---
title: "R Notebook"
output: html_notebook
---





```{r}
source("functions/functions_phylo_signal.R")
library(ape)
library(apTreeshape)
library(aricode)
library(igraph)
library(ggplot2)
library("vegan")
```





### get paths simulations results

```{r}
path_sim_fac <- "/Users/alexf/Desktop/PhD_Fuster-Calvo/Chapter 2 - Network_phylogeny/Network-Phylogeny/data/selection_evolution/facilitation"
file_paths_fac <- list.files(path = path_sim_fac, pattern = ".rds", full.names = TRUE)



path_sim_comp <- "/Users/alexf/Desktop/PhD_Fuster-Calvo/Chapter 2 - Network_phylogeny/Network-Phylogeny/data/selection_evolution/competition"
file_paths_comp <- list.files(path = path_sim_comp, pattern = ".rds", full.names = TRUE)


path_sim_fw <- "/Users/alexf/Desktop/PhD_Fuster-Calvo/Chapter 2 - Network_phylogeny/Network-Phylogeny/data/selection_evolution/foodweb1"
file_paths_fw <- list.files(path = path_sim_fw, pattern = ".rds", full.names = TRUE)


```




# Compute correlation phylogenetic signal - time for each simulation


```{r}

# facilitation
cor_fac <- compute_cor_phylosig_time_comp.fac(list_sim = file_paths_fac)

cor_fac$interaction <- rep("facilitation", times = nrow(cor_fac))


# competition

cor_comp <- compute_cor_phylosig_time_comp.fac(list_sim = file_paths_comp)

cor_comp$interaction <- rep("competition", times = nrow(cor_comp))


# foodweb

cor_fw <- compute_cor_phylosig_time_comp.fac(list_sim = file_paths_fw)

cor_fw$interaction <- rep("foodweb", times = nrow(cor_fw))


# Neutral [TODO]




### Merge data


df <- rbind(cor_fac,cor_comp,cor_fw)

#saveRDS(df, "../data/df_results_phylo_sims.RDS")

```



```{r}

ggplot(cor_fw, aes(x = timesteps, y = phylo.cor.mean, group = sim))+
geom_line(color="black", linetype="twodash")+
  #geom_point(aes(fill = sign_mean, color=sign_mean), size=2, alpha = 0.7) +
  theme_bw()+
    my.theme+
   # scale_colour_manual(values = c("black", "red"))+
    ggtitle("foodweb")+
xlab("timesteps")+
  ylab("Phylogenetic signal")


ggplot(cor_comp, aes(x = timesteps, y = phylo.cor.mean, group = sim))+
geom_line(color="black", linetype="twodash")+
  #geom_point(aes(fill = sign_mean, color=sign_mean), size=2, alpha = 0.7) +
  theme_bw()+
    my.theme+
   # scale_colour_manual(values = c("black", "red"))+
    ggtitle("competition")+
xlab("timesteps")+
  ylab("Phylogenetic signal")

ggplot(cor_fac, aes(x = timesteps, y = phylo.cor.mean, group = sim))+
geom_line(color="black", linetype="twodash")+
  #geom_point(aes(fill = sign_mean, color=sign_mean), size=2, alpha = 0.7) +
  theme_bw()+
    my.theme+
   # scale_colour_manual(values = c("black", "red"))+
    ggtitle("facilitation")+
xlab("timesteps")+
  ylab("Phylogenetic signal")

```

