---
title: "Obtain phylogenetic and interaction distances and compute phylogenetic signal - N simulations"
output: html_notebook
description: this script runs all steps from the script compute_phylosignal_1simularion.Rmd for each simulation results that we saved with the simulation_(interaction name).Rmd scripts and plots the phylogenetic signal over time for n simulations.
---



## ADD PLOT WITH ALL SPP RICHNESS curves



```{r}
source("functions/functions_phylosignal_nsimulations.R")
source("functions/functions_phylosignal.R")
library(ape)
library(apTreeshape)
library(aricode)
library(igraph)
library(ggplot2)
library(vegan)
library(ade4)
```



```{r}
my.theme<-theme(axis.text=element_text(size=12),
                axis.title = element_text(size = 14),
                legend.position = "top",
                legend.text=element_text(size=10),
                legend.title = element_text(size=12),
                plot.title = element_text(face="bold",size=14,margin=margin(0,0,20,0),hjust = 0.5),
                axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0)),
                axis.title.x = element_text(margin = margin(t = 15, r = 0, b = 0, l = 0)))
```




### get paths simulations results

Read the results of n simulations produced by simulation_fac_comp.Rmd, simulation_foodweb.Rmd, and simulation_neutral.Rmd scripts:

```{r}
#path_sim_fac <- "../data/selection_evolution/facilitation"
path_sim_fac <-"C:/Users/alexf/Desktop/PhD_Fuster-Calvo/Chapter 2 - Network_phylogeny/Network-Phylogeny/data/selection_evolution/facilitation"
file_paths_fac <- list.files(path = path_sim_fac, pattern = ".rds", full.names = TRUE)


#path_sim_comp <- "../data/selection_evolution/competition"
path_sim_comp <-"C:/Users/alexf/Desktop/PhD_Fuster-Calvo/Chapter 2 - Network_phylogeny/Network-Phylogeny/data/selection_evolution/competition"
file_paths_comp <- list.files(path = path_sim_comp, pattern = ".rds", full.names = TRUE)


#path_sim_fw <- "../data/selection_evolution/foodweb"
path_sim_fw <-"C:/Users/alexf/Desktop/PhD_Fuster-Calvo/Chapter 2 - Network_phylogeny/Network-Phylogeny/data/selection_evolution/foodweb"
file_paths_fw <- list.files(path = path_sim_fw, pattern = ".rds", full.names = TRUE)

#path_sim_n <- "../data/neutral"
path_sim_n <-"C:/Users/alexf/Desktop/PhD_Fuster-Calvo/Chapter 2 - Network_phylogeny/Network-Phylogeny/data/neutral"
file_paths_n <- list.files(path = path_sim_n, pattern = ".rds", full.names = TRUE)


```




# Compute correlation phylogenetic signal - time for each simulation


```{r}

# facilitation
cor_fac <- compute_cor_phylosig_time_comp.fac(list_sim = file_paths_fac)

cor_fac[[1]]$interaction <- rep("facilitation", times = nrow(cor_fac[[1]]))

#saveRDS(cor_fac, "../data/results_nsim_fac.RDS")


# competition

cor_comp <- compute_cor_phylosig_time_comp.fac(list_sim = file_paths_comp)

cor_comp$interaction <- rep("competition", times = nrow(cor_comp))


# foodweb
  

cor_fw <- compute_cor_phylosig_time_fw(list_sim = file_paths_fw)

cor_fw[[1]]$interaction <- rep("foodweb", times = nrow(cor_fw[[1]]))

#saveRDS(cor_fw, "../data/results_nsim_fw.RDS")


# Neutral [TODO]

cor_n <- compute_cor_phylosig_time_fw(list_sim = file_paths_n)

cor_n$interaction <- rep("neutral", times = nrow(cor_n))




### Merge data

df_results_phylosignal <- rbind(cor_fac,cor_comp,cor_fw, cor_n)

#saveRDS(df_results_phylo_sims, "../data/df_results_phylosignal.RDS")



```



# Plot the results


```{r}

df_fac <- df_results_phylo_sims[df_results_phylo_sims$interaction == "facilitation",]

p_fac <- ggplot(cor_fac[[1]], aes(x = timesteps, y = phylo.cor.mean, group = sim, col = sim))+
geom_line(color= cor_fac[[1]]$sim, linetype="solid",alpha = 0.7)+
  #geom_point(aes(fill = sign_mean, color=sign_mean), size=2, alpha = 0.7) +
  theme_bw()+
    my.theme+
   # scale_colour_manual(values = c("black", "red"))+
    ggtitle("facilitation")+
xlab("timesteps")+
  ylab("Phylogenetic signal")

df_comp <- df_results_phylo_sims[df_results_phylo_sims$interaction == "competition",]


p_comp <- ggplot(df_comp, aes(x = timesteps, y = phylo.cor.mean, group = sim))+
geom_line(color="black", linetype="twodash", alpha = 0.7)+
  #geom_point(aes(fill = sign_mean, color=sign_mean), size=2, alpha = 0.7) +
  theme_bw()+
    my.theme+
   # scale_colour_manual(values = c("black", "red"))+
    ggtitle("competition")+
xlab("timesteps")+
  ylab("Phylogenetic signal")

df_fw <- df_results_phylo_sims[df_results_phylo_sims$interaction == "foodweb",]


cor_fw1 <- cor_fw[cor_fw$sim != 3,]

p_fw <- ggplot(cor_fw[[1]], aes(x = timesteps, y = phylo.cor.mean, group = sim, col = sim))+
geom_line(color= cor_fw[[1]]$sim, linetype="solid",alpha = 0.7)+
  #geom_point(aes(fill = sign_mean, color=sign_mean), size=2, alpha = 0.7) +
  theme_bw()+
    my.theme+
   # scale_colour_manual(values = c("black", "red"))+
    ggtitle("foodweb")+
xlab("timesteps")+
  ylab("Phylogenetic signal")

df_n <- df_results_phylo_sims[df_results_phylo_sims$interaction == "neutral",]

p_n <- ggplot(df_n, aes(x = timesteps, y = phylo.cor.mean, group = sim))+
geom_line(color="black", linetype="twodash", alpha = 0.7)+
  #geom_point(aes(fill = sign_mean, color=sign_mean), size=2, alpha = 0.7) +
  theme_bw()+
    my.theme+
   # scale_colour_manual(values = c("black", "red"))+
    ggtitle("neutral")+
xlab("timesteps")+
  ylab("Phylogenetic signal")


ggarrange(
  
  p_fac,
  p_comp,
  p_fw,
  p_n,
  
  nrow = 2,
  ncol = 2
  
  
  
)

```

