---
title: "Invasion-assembled foodwebs"
output: html_notebook
---



```{r}
#install.packages("EnvStats")
#library(foreach) #To do parallel computiong

library(EnvStats)
library(foreach)

source("functions/functions_species_pool.R")
```



Simulation where species are drawn from a pool of 10 previously simulated communities.


I will need the pool of trait values of the present species in the 10 networks.


## Get pool of species (trait values)


Get data paths

```{r}


# Make a vector of all your file paths

file_paths_fac <- list.files(path = here::here("data/selection_evolution/facilitation/"), pattern = ".rds", full.names = TRUE)

file_paths_comp <- list.files(path = here::here("data/selection_evolution/competition/"), pattern = ".rds", full.names = TRUE)



pool_fac <- create_pool(list_file_paths = file_paths_fac)

pool_comp <- create_pool(list_file_paths = file_paths_comp)


#saveRDS(pool_fac, file = "../data/invasion/pools/pool_fac.rds")

#saveRDS(pool_comp, file = "../data/invasion/pools/pool_comp.rds")

```





# Simulations



